dist: xenial
sudo: required

language: python

python:
  - "3.7"

os:
  - linux

cache:
  pip: true
  directories:
  - "~/.platformio"
  - $HOME/astyle

install:
  - pip install -U platformio

before_script:
  - sh test/install_astyle.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - export ARTISTIC_STYLE_OPTIONS=".astylerc"
  - astyle -Q `find . -name *.cpp -o -name *.h` > astyle.out
  - TEST=$(cat astyle.out | wc -l)
  - |
      if [[ $TEST -ne 0 ]]; then
        cat astyle.out
        git --no-pager diff
        echo "Please fix style issues as shown above"
        exit 1
      fi

notifications:
  email:
    on_success: change
    on_failure: change
